# Step 1: Build the React app
FROM node:18 AS build

WORKDIR /app
COPY package.json ./
RUN yarn install

COPY . ./
RUN yarn build

# Step 2: Serve the React app using a lightweight web server
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
